spring:
  data:
    mongodb:
      auto-index-creation: true
      host: localhost
      port: 27017
      authentication-database: admin
      username: root
      password: root
      database: catalog
