version: '3'
services:
  mongodb:
    image: mongo
    #command: mongod --smallfiles
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: catalog
    volumes:
      - ./docker-volumes/mongo/data:/data/db      
    networks:
      - store-network
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: root
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
    links:
      - mongodb
    networks:
      - store-network
  redis:
    image: bitnami/redis
    ports:
      - 6379:6379
    environment:
#      REDIS_PASSWORD: password123
      ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - store-network
  redis-gui:
    image: marian/rebrow
    ports:
      - 5001:5001
    environment:
      REDIS_PASSWORD: password123
    links:
      - redis
    networks:
      - store-network
networks: 
    store-network:
      driver: bridge